#!/bin/bash
MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"

# Initialize constants here
export REGEX='^\[TA[0-9]+\] .+'

if [[ $FILE_CONTENT =~ $REGEX ]]; then
  echo "Good commit!"
else
  echo "Invalid commit message: $FILE_CONTENT"
  exit 1
fi

exit 0